services:
  redis:
    image: redis:7-alpine
    container_name: redis_shared
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - rede_publica
volumes:
  redis_data:
networks:
  rede_publica:
